### ISSUE TITLE
Filtering of dates is not working

### ISSUE THREAD

**Issue by dimangulov** [telerik/kendo-angular-demo-aspnetcore-data#3]
Example request: http://localhost:63106/api/expenses?filter=date~gte~2017-05-01T00:00:00.000Z&page=1&sort=date-desc&pageSize=5
Result: 
<h1>An unhandled exception occurred while processing the request.</h1>
<div class="titleerror">FilterParserException: Expected token</div>
<p class="location">Kendo.Mvc.Infrastructure.Implementation.FilterLexer.Tokenize()</p>

**Comment by rkonstantinov** [comment]
This should be fixed using a new version of `kendo-data-query` package
